kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ollama-sc
  namespace: ollama
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ollama-data-pv
spec:
  storageClassName: ollama-sc
  capacity:
    storage: "<STORAGE>"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path:   "<NFS_PATH>"
    server: "<SERVER_IP>"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-data-pvc
  namespace: ollama
spec:
  storageClassName: ollama-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "<STORAGE>"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        command: ["ollama", "serve", "--port", "11434"]
        ports:
        - containerPort: 11434
        resources:
          limits:
            cpu: "6"
            memory: "12Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-data
        readinessProbe:
          httpGet:
            path: /health
            port: 11434
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 20
      restartPolicy: Always
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama
spec:
  type: LoadBalancer
  loadBalancerIP: 10.2.2.10
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 11434
  selector:
    app: ollama