kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ollama-sc
  namespace: ollama
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ollama-data-pv
spec:
  storageClassName: ollama-sc
  capacity:
    storage: "<STORAGE>"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path:   "<NFS_PATH>"
    server: "<SERVER_IP>"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-data-pvc
  namespace: ollama
spec:
  storageClassName: ollama-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "<STORAGE>"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        command: ["ollama", "serve"]
        ports:
        - containerPort: 11434
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        resources:
          limits:
            cpu: "6"
            memory: "12Gi"
          requests:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-data
      restartPolicy: Always
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama
spec:
  type: LoadBalancer
  loadBalancerIP: 10.2.2.10
  ports:
  - name: tcp
    protocol: TCP
    port: 11434       # porta externa do LB
    targetPort: 11434 # porta do pod
  selector:
    app: ollama